services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80 
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-net
  db:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - laravel-net
  app:
    build: ./docker/php/
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000
    networks:
      - laravel-net
volumes:
  db-data:

networks:
  laravel-net:
